import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Faucet.module.css'
import React, { useEffect, useRef, useState } from "react";

export default function TokenA() {
  const [targetAddress, setTargetAddress] = useState("")
  const [loading, setLoading] = useState(false);

  const [ethBalance, setEtherBalance] = useState(0);

  const web3ModalRef = useRef();
  // walletConnected keep track of whether the user's wallet is connected or not
  const [walletConnected, setWalletConnected] = useState(false);

  const connectWallet = async () => {
    try {
      // Get the provider from web3Modal, which in our case is MetaMask
      // When used for the first time, it prompts the user to connect their wallet
      const signer = await getProviderOrSigner(true);
      const address = await signer.getAddress();
      setTargetAddress(address)
      setWalletConnected(true);
    } catch (err) {
      console.error(err);
    }
  };

  const getProviderOrSigner = async (needSigner = false) => {
    // Connect to Metamask
    // Since we store `web3Modal` as a reference, we need to access the `current` value to get access to the underlying object
    const provider = await web3ModalRef.current.connect();
    const web3Provider = new providers.Web3Provider(provider);

    // If user is not connected to the Rinkeby network, let them know and throw an error
    const { chainId } = await web3Provider.getNetwork();
    if (chainId !== 4) {
      window.alert("Change the network to Rinkeby");
      throw new Error("Change network to Rinkeby");
    }

    if (needSigner) {
      const signer = web3Provider.getSigner();
      return signer;
    }
    return web3Provider;
  };

  const sendTokens = () => {
    
  }

  /*
      renderButton: Returns a button based on the state of the dapp
  */
      const renderButton = () => {
        // If wallet is not connected, return a button which allows them to connect their wllet
        if (!walletConnected) {
          return (
            <button onClick={connectWallet} className={styles.formMainButton}>
              Connect your wallet
            </button>
          );
        } 
    
        // If we are currently waiting for something, return a loading button
        if (loading) {
          return <button className={styles.formMainButton}>Loading...</button>;
        }
    
        return (
          <button onClick={sendTokens} className={styles.formMainButton}>
              Get Tokens
            </button>
        )
      };
    

  return (
    <div className={styles.container}>
      <Head>
        <title>Token A Faucet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Token A Faucet
        </h1>
        <p>
          Get some token A now, and start testing!
        </p>
        <form className={styles.faucetForm}>
          <input className={styles.faucetInput} value={targetAddress} onChange={e =>setTargetAddress(e.target.value)} placeholder="Paste your 0x... address" />
          {renderButton()}
          
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
