import Head from "next/head";
import Image from "next/image";
import { BigNumber, providers, utils } from "ethers";
import styles from "../../styles/Dex.module.css";
import React, { useEffect, useRef, useState } from "react";
import Web3Modal from "web3modal";

export default function NotPancakeSwap() {
  const [loading, setLoading] = useState(false);

  const [ethBalance, setEtherBalance] = useState(0);
  const [etherBalanceContract, setEtherBalanceContract] = useState(0);


  const web3ModalRef = useRef();
  // walletConnected keep track of whether the user's wallet is connected or not
  const [walletConnected, setWalletConnected] = useState(false);

  const connectWallet = async () => {
    try {
      // Get the provider from web3Modal, which in our case is MetaMask
      // When used for the first time, it prompts the user to connect their wallet
      await getProviderOrSigner();
      setWalletConnected(true);
    } catch (err) {
      console.error(err);
    }
  };

  const getProviderOrSigner = async (needSigner = false) => {
    // Connect to Metamask
    // Since we store `web3Modal` as a reference, we need to access the `current` value to get access to the underlying object
    const provider = await web3ModalRef.current.connect();
    const web3Provider = new providers.Web3Provider(provider);

    // If user is not connected to the Rinkeby network, let them know and throw an error
    const { chainId } = await web3Provider.getNetwork();
    if (chainId !== 4) {
      window.alert("Change the network to Rinkeby");
      throw new Error("Change network to Rinkeby");
    }

    if (needSigner) {
      const signer = web3Provider.getSigner();
      return signer;
    }
    return web3Provider;
  };

  const getAmounts = async () => {
    try {
      const provider = await getProviderOrSigner(false);
      const signer = await getProviderOrSigner(true);
      const address = await signer.getAddress();
      // get the amount of eth in the user's account
      const _ethBalance = await getEtherBalance(provider, address);
     
      // Get the ether reserves in the contract
      const _ethBalanceContract = await getEtherBalance(provider, null, true);
      setEtherBalance(_ethBalance);
      setEtherBalanceContract(_ethBalanceContract);
    } catch (err) {
      console.error(err);
    }
  };

  const performSwap = () => {
    
  }

  useEffect(() => {
    // if wallet is not connected, create a new instance of Web3Modal and connect the MetaMask wallet
    if (!walletConnected) {
      // Assign the Web3Modal class to the reference object by setting it's `current` value
      // The `current` value is persisted throughout as long as this page is open
      web3ModalRef.current = new Web3Modal({
        network: "rinkeby",
        providerOptions: {},
        disableInjectedProvider: false,
      });
      // connectWallet();
      // getAmounts();
    }
  }, [walletConnected]);

  /*
      renderButton: Returns a button based on the state of the dapp
  */
  const renderButton = () => {
    // If wallet is not connected, return a button which allows them to connect their wllet
    if (!walletConnected) {
      return (
        <button onClick={connectWallet} className={styles.formMainButton}>
          Connect your wallet
        </button>
      );
    } 

    // If we are currently waiting for something, return a loading button
    if (loading) {
      return <button className={styles.formMainButton}>Loading...</button>;
    }

    return (
      <button onClick={performSwap} className={styles.formMainButton}>
          Swap
        </button>
    )
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Not Pancake Swap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.logo}>
          U
        </div>
        <div className={styles.headerCenter}>
          Swap
        </div>
        <div className={styles.headerRight}>
          <div className={styles.networkDropdown}>
            Ethereum
          </div>
          <button className={styles.connectButton}>
            Connect Wallet
          </button>
          <button className={styles.moreButton}>
            ...
          </button>
        </div>
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>Not Pancake Swap</h1>
        <p className={styles.description}>
          <a href="" className={styles.link}>Go to Not UniSwap</a>
        </p>
        <div className={styles.form}>
          <div className={styles.formHeader}>
            <h2 className={styles.formTitle}>Not Pancake Swap</h2>
            <button className={styles.formButton}>S</button>
          </div>
          <div className={styles.formBody}>
          <label className={styles.formLabel}>
              <div className={styles.formLabelTop}>
                <input
                  className={styles.formInput}
                  type="text"
                  placeholder="Pokemon 1"
                />
                <button className={styles.formButton}>
                  <Image
                    src="/images/icons/pokeball.png"
                    alt="pokeball"
                    width={24}
                    height={24}
                  />
                  ETH
                  V
                </button>
              </div>
              <div className={styles.formLabelBottom}>
                <p className={styles.formLabelBottomText}>$23,299</p>
              </div>
            </label>
            <button className={styles.formCenterButton}>
              V
            </button>
            <label className={styles.formLabel}>
              <div className={styles.formLabelTop}>
                <input
                  className={styles.formInput}
                  type="text"
                  placeholder="Pokemon 2"
                />
              </div>
              <div className={styles.formLabelBottom}>
                <p className={styles.formLabelBottomText}>$23,299</p>
              </div>
            </label>
            {/* <button className={styles.formMainButton}>Connect Wallet</button> */}
            {renderButton()}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
